# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Code_analysis
  displayName: Analyse the petclinic code
  jobs:
  - job: Analyse_Code
    displayName: Put the code through SonarQube
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'azuresonarqube'
        scannerMode: 'Other'
    - task: SonarQubeAnalyze@4
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'